# pnpm Workspace Configuration
# Defines workspace packages for monorepo management

packages:
  # Backend application
  - 'apps/backend'

  # Frontend application
  - 'apps/frontend'

  # Shared packages
  - 'packages/*'
